import React from 'react';
import { ReactComponent as Cog } from './icons/cog.svg'
import { ReactComponent as Arrow } from './icons/arrow.svg';
import { ReactComponent as NDA } from './icons/nda.svg';
import { ReactComponent as Permission } from './icons/permission.svg';
import { ReactComponent as Contract } from './icons/contract.svg';
import { ReactComponent as ShoppingCart } from './icons/shopping-cart.svg';
import { ReactComponent as Sample } from './icons/blood-sample.svg';
import { ReactComponent as PurchaseOrder } from './icons/purchase.svg';
import { ReactComponent as Shipment } from './icons/shipment.svg';
import { ReactComponent as Engineer } from './icons/engineer.svg';
import { ReactComponent as HumanResources } from './icons/human-resources.svg';
import { ReactComponent as OnlineSupport } from './icons/online-support.svg';
import { ReactComponent as Tools } from './icons/tools.svg';
import { ReactComponent as Bolt } from './icons/bolt.svg';
import { ReactComponent as Procurement } from './icons/buy-button.svg';
import { ReactComponent as Question } from './icons/question.svg';
import { ReactComponent as Sunbed } from './icons/sunbed.svg';
import { ReactComponent as Bell } from './icons/bell.svg'
import { ReactComponent as Messenger } from './icons/messenger.svg'
import { ReactComponent as Caret } from './icons/caret.svg'
import { ReactComponent as Plus } from './icons/plus.svg'
import { ReactComponent as UserEdit } from './icons/user-edit.svg'
import { ReactComponent as Key } from './icons/key.svg'
import { ReactComponent as Dashboard } from './icons/dashboard.svg'
import { ReactComponent as Department } from './icons/department.svg'
import { ReactComponent as ArrowDown } from './icons/arrow-down.svg'
import { ReactComponent as HR } from './icons/hr.svg'
import { ReactComponent as Team } from './icons/team.svg'
import { ReactComponent as VehicleProduction } from './icons/productivity.svg'

export const CogIcon = () => <Cog />
export const ArrowIcon = () => <Arrow />
export const NDAIcon = () => <NDA />
export const PermissionIcon = () => <Permission />
export const ContractIcon = () => <Contract />
export const ShoppingCartIcon = () => <ShoppingCart />
export const SampleIcon = () => <Sample />
export const PurchaseOrderIcon = () => <PurchaseOrder />
export const ShipmentIcon = () => <Shipment />
export const EngineerIcon = () => <Engineer />
export const HumanResourcesIcon = () => <HumanResources />
export const OnlineSupportIcon = () => <OnlineSupport />
export const ToolsIcon = () => <Tools />
export const BoltIcon = () => <Bolt />
export const ProcurementIcon = () => <Procurement />
export const QuestionIcon = () => <Question />
export const SunbedIcon = () => <Sunbed />
export const BellIcon = () => <Bell />
export const MessengerIcon = () => <Messenger />
export const CaretIcon = () => <Caret />
export const PlusIcon = () => <Plus />
export const UserEditIcon = () => <UserEdit />
export const KeyIcon = () => <Key />
export const DashboardIcon = () => <Dashboard />
export const DepartmentIcon = () => <Department />
export const ArrowDownIcon = () => <ArrowDown />
export const HRIcon = () => <HR />
export const TeamIcon = () => <Team />
export const VehicleProductionIcon = () => <VehicleProduction />
